package com.kaya.credit.engine;

public enum CreditCheckResponse {
    TRUE,
    SECTOR_LIMIT_NOT_DEFINED,
    INVALID_TRADE_ACTION_TYPE,
    BIGGER_THAN_PORTFOLIO_MAX_VALUE,
    TRADE_EXCEEDS_SECTOR_LIMIT,
    PORTFOLIO_NOT_AVAILABLE,
    PORTFOLIO_NOT_HAVE_ENOUGH_AMOUNT_TO_SELL,
    SECURITY_SECTOR_NOT_DEFINED
}
